MvcBookStore/MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
using PagedList;
using PagedList.Mvc;

namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        // Tạo một đối tượng chứa toàn booh CSDL từ dbQLBansach
        
            dbQLBansachDataContext data = new dbQLBansachDataContext();
        
        // GET: BookStore
        private List<SACH> Laysachmoi(int count)
        {
            //Sắp xếp giảm dần theo Ngaycapnhat, lấy count đòng đầu
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            //Tạo biến số trang
            int pageSize = (page ?? 1);


            //Lấy 5 quyển sách mới nhất
            var sachmoi = Laysachmoi(5);
            return View(sachmoi);
        }
        [ChildActionOnly]
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult SPTheochude(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
        }
    }
}

MvcBookStore/MvcBookStore/Controllers/NguoidungController.cs
using MvcBookStore.Models;
using Sitecore.FakeDb;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XAct.Library.Settings;

namespace MvcBookStore.Controllers
{
    public class NguoidungController : Controller
    {
        dbQLBansachDataContext db = new dbQLBansachDataContext();
        // GET: Nguoidung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        //POST: hàm Dangky(post) nhận sữ liệu từ trang Dangky và thực hiện việc tạo mới dữ liệu
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến
            var hoten = collection["HotenKh"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/đ/yyyy}", collection["Ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ & tên không được để trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Thiếu tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Thiếu mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Nhập lại mật khẩu";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Thiếu Email";
            }
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Thiếu sđt";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);
                db.KHACHHANGs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Thiếu tên";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Thiếu mật khẩu";
            }
            else
            {
                //Gán giá trị cho đối tượng mới(kh)
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Taikhoan"] = kh;
                }
                else
                    ViewBag.Thongbao = "Tên ĐN hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

MvcBookStore/MvcBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcBookStore/MvcBookStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>NICE</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="~/img/favicon.ico" />
    <link rel="stylesheet" href="~/CSS/style.css" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.jcarousel.min.js"></script>
    <!--[if IE 6]>
        <script type="text/javascript" src="js/png-fix.js"></script>
    <![endif]-->
    <script type="text/javascript" src="~/Scripts/functions.js"></script>
</head>
<body>

    <!-- Header -->
    <div id="header" class="shell">
        <div id="logo"><h1><a href="#">BestSeller</a></h1><span><a href="#">OK</a></span></div>
        <!-- Navigation -->
        <div id="navigation">
            <ul>
                <li><a href="#" class="active">Home</a></li>
                <li><a href="#">Products</a></li>
                <li><a href="#">Promotions</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contacts</a></li>
            </ul>
        </div>
        <!-- End Navigation -->
        <div class="cl">&nbsp;</div>
        <!-- Login-details -->
        <div id="login-details">
            <p>Welcome, <a href="#" id="user">Guest</a> .</p><p><a href="#" class="cart"><img src="~/img/cart-icon.png" alt="" /></a>Shopping Cart (0) <a href="#" class="sum">$0.00</a></p>
        </div>
        <!-- End Login-details -->
    </div>
    <!-- End Header -->
    <!-- Slider -->
    <div id="slider">
        <div class="shell">
            <ul>
                <li>
                    <div class="image">
                        <img src="~/img/books.png" alt="" />
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">Pellentesque congue lorem quis massa blandit non pretium nisi pharetra</p>
                        <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id odio in tortor scelerisque dictum. Phasellus varius sem sit amet metus volutpat vel vehicula nunc lacinia.</p>
                        <a href="#" class="read-more-btn">Read More</a>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <img src="~/img/books.png" alt="" />
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">Pellentesque congue lorem quis massa blandit non pretium nisi pharetra</p>
                        <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id odio in tortor scelerisque dictum. Phasellus varius sem sit amet metus volutpat vel vehicula nunc lacinia.</p>
                        <a href="#" class="read-more-btn">Read More</a>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <img src="~/img/books.png" alt="" />
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">Pellentesque congue lorem quis massa blandit non pretium nisi pharetra</p>
                        <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id odio in tortor scelerisque dictum. Phasellus varius sem sit amet metus volutpat vel vehicula nunc lacinia.</p>
                        <a href="#" class="read-more-btn">Read More</a>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <img src="~/img/books.png" alt="" />
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">Pellentesque congue lorem quis massa blandit non pretium nisi pharetra</p>
                        <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id odio in tortor scelerisque dictum. Phasellus varius sem sit amet metus volutpat vel vehicula nunc lacinia.</p>
                        <a href="#" class="read-more-btn">Read More</a>
                    </div>
                </li>
            </ul>
            <div class="nav">
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
            </div>
        </div>
    </div>
    <!-- End Slider -->
    <!-- Main -->
    <div id="main" class="shell">
        <!-- Sidebar -->
        <div id="sidebar">
            <div class="col-md-3">

                @Html.Action("Chude", "BookStore")

            </div>
            <div class="col-md-3">
                @Html.Action("Nhaxuatban", "BookStore")
            </div>
        </div>
        <!-- End Sidebar -->
        <!-- Content -->
        <div id="content">
            <!-- Products -->
            <div class="products">


                <!-- End Products -->
            </div>
            <div class="cl">&nbsp;</div>
            <!-- Best-sellers -->
            <div id="best-sellers">
                <h3>Best Sellers</h3>
                <div>
                    @RenderBody()
                </div>
            </div>
            <!-- End Best-sellers -->
        </div>
        <!-- End Content -->
        <div class="cl">&nbsp;</div>
    </div>
    <!-- End Main -->
    <!-- Footer -->
    <div id="footer" class="shell">
        <div class="top">
            <div class="cnt">
                <div class="col about">
                    <h4>About BestSellers</h4>
                    <p>Nulla porttitor pretium mattis. Mauris lorem massa, ultricies non mattis bibendum, semper ut erat. Morbi vulputate placerat ligula. Fusce <br />convallis, nisl a pellentesque viverra, ipsum leo sodales sapien, vitae egestas dolor nisl eu tortor. Etiam ut elit vitae nisl tempor tincidunt. Nunc sed elementum est. Phasellus sodales viverra mauris nec dictum. Fusce a leo libero. Cras accumsan enim nec massa semper eu hendrerit nisl faucibus. Sed lectus ligula, consequat eget bibendum eu, consequat nec nisl. In sed consequat elit. Praesent nec iaculis sapien. <br />Curabitur gravida pretium tincidunt.  </p>
                </div>
                <div class="col store">
                    <h4>Store</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Special Offers</a></li>
                        <li><a href="#">Log In</a></li>
                        <li><a href="#">Account</a></li>
                        <li><a href="#">Basket</a></li>
                        <li><a href="#">Checkout</a></li>
                    </ul>
                </div>
                <div class="col" id="newsletter">
                    <h4>Newsletter</h4>
                    <p>Lorem ipsum dolor sit amet  consectetur. </p>
                    <form action="" method="post">
                        <input type="text" class="field" value="Your Name" title="Your Name" />
                        <input type="text" class="field" value="Email" title="Email" />
                        <div class="form-buttons"><input type="submit" value="Submit" class="submit-btn" /></div>
                    </form>
                </div>
                <div class="cl">&nbsp;</div>
                <div class="copy">
                    <p>&copy; <a href="#">BestSeller.com</a>. Design by <a href="http://css-free-templates.com/">CSS-FREE-TEMPLATES.COM</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer -->
</body>
</html>

MvcBookStore/MvcBookStore/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>NICE</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="~/images/favicon.ico" />
    <link rel="stylesheet" href="~/Content/style1.css" type="text/css" media="all" />
    
    <script type="text/javascript" src="~/Scripts/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.jcarousel.min.js"></script>
    <!--[if IE 6]>
        <script type="text/javascript" src="js/png-fix.js"></script>
    <![endif]-->
    <script type="text/javascript" src="~/Scripts/functions.js"></script>
</head>
<body>

    <!-- Header -->
    <div id="header" class="shell">
        <div id="logo"><h1><a href="#">BestSeller</a></h1><span><a href="#">OK</a></span></div>
        <!-- Navigation -->
        <div id="navigation">
            <ul>
                <li>@Html.ActionLink("TRANG CHỦ", "Index", "BookStore")</li>
                <li>@Html.ActionLink("ĐĂNG KÝ", "Dangky", "Nguoidung")</li>
                <li>@Html.ActionLink("ĐĂNG NHẬP", "Dangnhap", "Nguoidung")</li>
                <li>@Html.ActionLink("GIỎ HÀNG", "GiohangPartial", "GioHang")</li>
            </ul>
        </div>
        <!-- End Navigation -->
        <div class="cl">&nbsp;</div>
        <!-- Login-details -->
        <div id="login-details">
            <p>Welcome, <a href="#" id="user">Guest</a> .</p><p><a href="#" class="cart"><img src="~/img/cart-icon.png" alt="" /></a>Shopping Cart (0) <a href="#" class="sum">$0.00</a></p>
        </div>
        <!-- End Login-details -->
    </div>
    <!-- End Header -->
    <!-- Slider -->
    <div id="slider">
        <div class="shell">
            <ul>
                <li>
                    <div class="image">
                        <center>
                            <img src="~/images/mot-minh-song-trong-rung.jpg" width="250" height="350" />
                        </center>
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">WALDEN - MỘT MÌNH SỐNG TRONG RỪNG</p>
                        <p class="description">Lĩnh vực đề cử: Sách cho người trẻ do cộng đồng sách trẻ bình chọn</p>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <center>
                            <img src="~/images/767.jpeg" width="250" height="350"/>
                        </center>
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">BÀ BOVARY</p>
                        <p class="description">Lĩnh vực đề cử: Văn học</p>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <center>
                            <img src="~/images/dostoyevski.jpg" width="250" height="350" />
                        </center>
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">ANH EM NHÀ KARAMAZOV</p>
                        <p class="description">Lĩnh vực đề cử: Văn học</p>
                    </div>
                </li>
                <li>
                    <div class="image">
                        <center>
                            <img src="~/images/11_1_6_135635.jpg" width="250" height="350"/>
                        </center>
                    </div>
                    <div class="details">
                        <h2>Bestsellers</h2>
                        <h3>Special Offers</h3>
                        <p class="title">BỐ GIÀ</p>
                        <p class="description">Lĩnh vực đề cử: Văn học</p>
                    </div>
                </li>
            </ul>
            <div class="nav">
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
            </div>
        </div>
    </div>
    <!-- End Slider -->
    <!-- Main -->
    <div id="main" class="shell">
        <!-- Sidebar -->
        <div id="sidebar">
            <ul class="categories">
                <li>
                    <h4>CHỦ ĐỀ</h4>
                    <ul>
                        @Html.Action("Chude", "BookStore")
                    </ul>
                </li>
            
            <li>
                <h4>NHÀ XUẤT BẢN</h4>
                <ul>
                @Html.Action("Nhaxuatban", "BookStore")
                </ul>
            </li>
            </ul>
        </div>
        <!-- End Sidebar -->
        <!-- Content -->
        <div id="content">
            <!-- Products -->
            <div class="products">
                <h3></h3>
                <ul>
                        <div>
                        @RenderBody()
                        </div>
                    </li>
                </ul>

                <!-- End Products -->
            </div>
            <div class="cl">&nbsp;</div>
            <!-- Best-sellers -->
            <div id="best-sellers">
                
                
            </div>
            <!-- End Best-sellers -->
        </div>
        <!-- End Content -->
        <div class="cl">&nbsp;</div>
    </div>
    <!-- End Main -->
    <!-- Footer -->
    <div id="footer" class="shell">
        <div class="top">
            <div class="cnt">
                <div class="col about">
                    <h4>About BestSellers</h4>
                    <p>Nulla porttitor pretium mattis. Mauris lorem massa, ultricies non mattis bibendum, semper ut erat. Morbi vulputate placerat ligula. Fusce <br />convallis, nisl a pellentesque viverra, ipsum leo sodales sapien, vitae egestas dolor nisl eu tortor. Etiam ut elit vitae nisl tempor tincidunt. Nunc sed elementum est. Phasellus sodales viverra mauris nec dictum. Fusce a leo libero. Cras accumsan enim nec massa semper eu hendrerit nisl faucibus. Sed lectus ligula, consequat eget bibendum eu, consequat nec nisl. In sed consequat elit. Praesent nec iaculis sapien. <br />Curabitur gravida pretium tincidunt.  </p>
                </div>
                <div class="col store">
                    <h4>Store</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Special Offers</a></li>
                        <li><a href="#">Log In</a></li>
                        <li><a href="#">Account</a></li>
                        <li><a href="#">Basket</a></li>
                        <li><a href="#">Checkout</a></li>
                    </ul>
                </div>
                <div class="col" id="newsletter">
                    <h4>Newsletter</h4>
                    <p>Lorem ipsum dolor sit amet  consectetur. </p>
                    <form action="" method="post">
                        <input type="text" class="field" value="Your Name" title="Your Name" />
                        <input type="text" class="field" value="Email" title="Email" />
                        <div class="form-buttons"><input type="submit" value="Submit" class="submit-btn" /></div>
                    </form>
                </div>
                <div class="cl">&nbsp;</div>
                <div class="copy">
                    <p>&copy; <a href="#">BestSeller.com</a>. Design by <a href="http://css-free-templates.com/">CSS-FREE-TEMPLATES.COM</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer -->
</body>
</html>